twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    date:
        format: 'l d F Y à H:i'
        interval_format: '%d jours'
when@test:
    twig:
        strict_variables: true
