appointments_hours:
    path: /appointments/hours
    controller: App\Controller\AppointmentController::getAppointmentHours


controllers:
    resource: ../src/Controller/
    type: attribute


api_get_subcategories:
    path: /category
    controller: App\Controller\TeacherController::getSubCategoryByCategory
    methods: [GET]